apiVersion: v1
kind: PersistentVolume
metadata:
  name: ab-testing-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/ab-testing
    type: DirectoryOrCreate
